### ISSUE TITLE
Quizes for reputation gain

### ISSUE THREAD

**Issue by hubbyist** [particle-clicker/particle-clicker#105]
Idea:
Quizes composed of two or three questions about the information given in the game modals may make game more challenging I think. 

Proposal:
Reputation gain will be bind to quizes. Each will start with the set maximum reputation. Each wrong answer will cause point loose up to 5 tries when all possible answers for the question depleted. Formula will be as follows:

    MaximunPossibleReputationGain \times (1/NumberOfQuestions) \times \sum _{k=1}^{k=NumberOfQuestions}(1 - 0.2 \times {NumberOfTries_n})

For example when a 100 points quiz of three questions, is answered with 2,3,4 tries respectively, reputation gain will be:

     (100 * (0.333 * (0.60 + 0.40 + 0.20)))

More harder quizes may be added about information not given by the game for special in game bonuses later.

WDYT?

**Comment by FoxyPlayGamer435** [comment]
I think there is a reason for why they didn't do this. Because kids can just look up the anwsers.

**Comment by rhoadeswilliam1** [comment]
I think it's not a bad idea, but it takes away from the action element  of
the game. In order to make up for that maybe have crazy animations and
effects when the correct answer is chosen. Also I'd introduce it later in
the game not right away so that they are more eager to dive into the
information after they've been more "immersed". Perhaps make the player
feel like they've earned the right to quiz themselves. Also I think there's
nothing wrong with actually providing the answers in game or elsewhere let
them feel like they are getting sneaky about it, but in reality we are
encouraging learning. If they want to research, read, and learn even a
little bit to get a reward I think that's kick A! In fact I'd recommend
indexing an answers and explanations page with google under key words
particle clicker answers/cheats/quizzes and in the fine print at the bottom
put answers provided by Particle Clicker dev team. Also make it like if
they fail a few times just straight up give them the answers and give them
the points anyways. You don't want to introduce the idea of punishments,
failures or missed opportunities. There's enough opportunities in the real
world to take a loss... lol. One of the elements that I really enjoy about
this game is that even though there are optimal paths your points only go
up. It's very important that the feeling of progression not regression is
preserved. It's cool that after all this time people are appending and
trying to enhance the game. On maybe have infinite retries on the tests and
if they get all tests A or better it unlocks a color changing mode where
you can change the color schema (in a non breakable way i.e. can't pick
colors that don't have enough contrast).  That should add a bunch of work
for the Dev team if they are up to the challenge! Perhaps fork it and merge
it after testing.
[image: image.png]

**Comment by Dieforrobux** [comment]
I think it's not a bad idea, but it takes away from the action element  of
the game. In order to make up for that maybe have crazy animations and
effects when the correct answer is chosen. Also I'd introduce it later in
the game not right away so that they are more eager to dive into the
information after they've been more "immersed". Perhaps make the player
feel like they've earned the right to quiz themselves. Also I think there's
nothing wrong with actually providing the answers in game or elsewhere let
them feel like they are getting sneaky about it, but in reality we are
encouraging learning. If they want to research, read, and learn even a
little bit to get a reward I think that's kick A! In fact I'd recommend
indexing an answers and explanations page with google under key words
particle clicker answers/cheats/quizzes and in the fine print at the bottom
put answers provided by Particle Clicker dev team. Also make it like if
they fail a few times just straight up give them the answers and give them
the points anyways. You don't want to introduce the idea of punishments,
failures or missed opportunities. There's enough opportunities in the real
world to take a loss... lol. One of the elements that I really enjoy about
this game is that even though there are optimal paths your points only go
up. It's very important that the feeling of progression not regression is
preserved. It's cool that after all this time people are appending and
trying to enhance the game. On maybe have infinite retries on the tests and
if they get all tests A or better it unlocks a color changing mode where
you can change the color schema (in a non breakable way i.e. can't pick
colors that don't have enough contrast).  That should add a bunch of work
for the Dev team if they are up to the challenge! Perhaps fork it and merge
it after testing.
[image: image.png]

**Comment by Dieforrobux** [comment]
How? I Didn't post that.

**Comment by kdungs** [comment]
Great suggestion but we're not actively maintaining this. Small PRs are welcome but this would fundamentally change the game.
