### ISSUE TITLE
upgrade-lhcb seems not to work

### ISSUE THREAD

**Issue by caspar** [particle-clicker/particle-clicker#97]
No telling why...

**Comment by Tampa** [comment]
The cern hosted version seems to be missing these two upgrades, the github version will end up having 2.0M in reputation for CP research, this seems to be missing from the cern version.

**Comment by kdungs** [comment]
Yeah, this has been fixed in the GitHub version since about 2015. Since today (wow! what took them so long am I right?!) you can always play the latest version here:  https://particle-clicker.github.io/particle-clicker/

For more context, see: https://github.com/particle-clicker/particle-clicker/issues/102#issuecomment-1468816145.

**Comment by ntadej** [comment]
As there seems to be interest I'll also update the CERN version, but it may take a few days.
